"""Initial Migration

Revision ID: 196d988c6134
Revises: a497fe756ed6
Create Date: 2022-02-05 00:47:20.883109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196d988c6134'
down_revision = 'a497fe756ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'picture_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('picture_path', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
